/** @type { importCharacterConfig['character'] } */
const character = {
	//魏
	qj_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_jianxiong"],
		keGroup: ["han", "qun"],
	},
	qj_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qj_guicai", "qj_fankui"],
		keGroup: ["jin"],
	},
	qj_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_ganglie", "qj_qingjian"],
	},
	qj_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_tuxi"],
		keGroup: ["han", "qun"],
	},
	qj_xuchu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_luoyi"],
	},
	qj_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qj_qingzi", "qj_yiji"],
	},
	qj_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["qj_luoshen", "qj_qingguo"],
		keGroup: ["qun"],
	},
	qj_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["qj_shensu", "qj_shebian"],
	},
	qj_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_qiaobian"],
		keGroup: ["qun"],
	},
	qj_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_duanliang", "qj_jiezi"],
		keGroup: ["han"],
	},
	qj_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_weikui", "qj_lizhan"],
	},
	qj_dianwei: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["qj_qiangxi"],
		keGroup: ["qun"],
	},
	qj_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qj_quhu", "qj_jieming"],
		keGroup: ["han"],
	},
	qj_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qj_xingshang", "qj_fangzhu"],
	},
	qj_yuejin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_xiaoguo"],
	},
	//蜀
	qj_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_rende"],
		keGroup: ["han", "wei", "wu", "qun"],
	},
	qj_guanyu: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["qj_wusheng"],
		keGroup: ["han", "wei"],
	},
	qj_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_paoxiao"],
		keGroup: ["han", "wu"],
	},
	qj_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qj_guanxing", "qj_kongcheng"],
	},
	qj_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_longdan"],
		keGroup: ["han", "qun"],
	},
	qj_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_mashu", "qj_tieji"],
		keGroup: ["qun"],
	},
	qj_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["qj_jizhi", "qj_cangji"],
	},
	qj_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_liegong"],
		keGroup: ["qun"],
	},
	qj_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_kuanggu"],
		keGroup: ["qun"],
	},
	qj_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qj_lianhuan", "qj_niepan"],
		keGroup: ["wu"],
	},
	qj_wolong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qj_huoji", "qj_bazhen", "qj_kanpo"],
		keGroup: ["wu"],
	},
	qj_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["qj_xiangle", "qj_fangquan"],
		keGroup: ["jin"],
	},
	qj_menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_huoshou", "qj_zaiqi"],
		keGroup: ["qun"],
	},
	qj_zhurongfuren: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["qj_juxiang", "qj_lieren"],
		keGroup: ["qun"],
	},
	qj_ganfuren: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["qj_shushen", "qj_shenzhi"],
	},
	//吴
	qj_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_zhiheng"],
		keGroup: ["wei"],
	},
	qj_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_qixi"],
		keGroup: ["qun"],
	},
	qj_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_keji", "qj_mouduan"],
	},
	qj_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_kurou", "qj_zhaxiang"],
		keGroup: ["han"],
	},
	qj_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_yingzi", "qj_fanjian"],
		keGroup: ["qun"],
	},
	qj_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["qj_guose", "qj_liuli"],
	},
	qj_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["qj_qianxun", "qj_duoshi"],
	},
	qj_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["qj_jieyin", "qj_xiaoji"],
		keGroup: ["shu"],
	},
	qj_sunjian: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["qj_yinghun"],
		keGroup: ["han", "qun"],
	},
	qj_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["qj_tianxiang", "qj_hongyan"],
	},
	qj_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_tianyi", "qj_hanzhan"],
		keGroup: ["han", "qun"],
	},
	qj_zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_buqu", "qj_fenji"],
	},
	qj_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["qj_haoshi", "qj_dimeng"],
		keGroup: ["shu", "qun"],
	},
	qj_zhangzhao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["qj_zhijian", "qj_guzheng"],
		keGroup: ["han"],
	},
	qj_dingfeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_duanbing", "qj_fenxun"],
	},
	//群
	qj_huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["qj_jishi", "qj_chuli"],
		keGroup: ["han", "wei", "shu", "wu"],
	},
	qj_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["qj_wushuang", "qj_xiaomeng"],
		keGroup: ["han", "shu"],
	},
	qj_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qj_lijian", "qj_biyue"],
		keGroup: ["han"],
	},
	qj_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_luanji"],
		keGroup: ["han"],
	},
	qj_yanliangwenchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_shuangxiong"],
	},
	qj_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["qj_wansha", "qj_luanwu", "qj_weimu"],
		keGroup: ["han", "wei"],
	},
	qj_pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_mashu", "qj_menghan"],
		keGroup: ["wei"],
	},
	qj_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["qj_leiji", "qj_guidao"],
	},
	qj_caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qj_beige", "qj_duanchang"],
		keGroup: ["han", "wei"],
	},
	qj_mateng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_mashu", "qj_xiongyi"],
		keGroup: ["han"],
	},
	qj_jiling: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_shuangren"],
	},
	qj_tianfeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["qj_sijian", "qj_suishi"],
	},
	qj_panfeng: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_kuangfu"],
		keGroup: ["han"],
	},
	qj_zoushi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qj_huoshui", "qj_qingcheng"],
		keGroup: ["wei"],
	},
	qj_hansui: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_mashu", "qj_xiaoni"],
		keGroup: ["han"],
	},
	//晋
	qj_simayan: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["qj_chuitong", "qj_xingtu"],
	},
	qj_simashi: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_tairan", "qj_yimie"],
		keGroup: ["wei"],
	},
	qj_simazhao: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["qj_choufa", "qj_zhaoran"],
		keGroup: ["wei"],
	},
	qj_jiachong: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["qj_tongfa", "qj_beishi"],
	},
	qj_yanghu: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_rouke", "qj_shunliu"],
	},
	qj_wangyuanji: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["qj_shiren", "qj_jiexia"],
	},
	qj_xiahouhui: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["qj_yishi", "qj_shidu"],
		keGroup: ["wei"],
	},
	qj_jinsimayi: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["qj_quanbian", "qj_zhouting"],
		keGroup: ["wei"],
	},
	qj_zhangchunhua: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["qj_shangshi", "qj_ejue"],
		keGroup: ["wei"],
	},
	qj_zhanghuyuechen: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_guoyi"],
		keGroup: ["wei"],
	},
	qj_yanghuiyu: {
		sex: "female",
		group: "jin",
		hp: 3,
		skills: ["qj_ciwei", "qj_caiyuan"],
	},
	qj_wangjun: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_keqing"],
	},
	qj_wenyang: {
		sex: "male",
		group: "jin",
		hp: 5,
		skills: ["qj_lvli", "qj_duoqi"],
		keGroup: ["wei", "wu"],
	},
	qj_shibao: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_qianqu"],
	},
	qj_zhanghua: {
		sex: "male",
		group: "jin",
		hp: 3,
		skills: ["qj_fuli", "qj_fengwu"],
	},
	//汉
	qj_liuxie: {
		sex: "male",
		group: "han",
		hp: 3,
		skills: ["qj_tianming", "qj_mizhao"],
		keGroup: ["wei", "qun"],
	},
	qj_liubian: {
		sex: "male",
		group: "han",
		hp: 3,
		skills: ["qj_shiyuan", "qj_dushi"],
		keGroup: ["qun"],
	},
	qj_zhangrang: {
		sex: "male",
		group: "han",
		hp: 3,
		skills: ["qj_taoluan"],
	},
	qj_hejin: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_mouzhu", "qj_yanhuo"],
	},
	qj_wangyun: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_lianji", "qj_dingzhu"],
	},
	qj_wangrong: {
		sex: "female",
		group: "han",
		hp: 3,
		skills: ["qj_minsi", "qj_fusong"],
	},
	qj_fuhuanghou: {
		sex: "female",
		group: "han",
		hp: 3,
		skills: ["qj_zhuikong", "qj_qiuyuan"],
	},
	qj_fuwan: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_moukui"],
	},
	qj_dongcheng: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_chengzhao"],
		keGroup: ["qun"],
	},
	qj_tangji: {
		sex: "female",
		group: "han",
		hp: 3,
		skills: ["qj_aiwu", "qj_juebie"],
	},
	qj_caiyong: {
		sex: "male",
		group: "han",
		hp: 3,
		skills: ["qj_zhudian", "qj_botong"],
		keGroup: ["qun"],
	},
	qj_huangfusong: {
		sex: "male",
		group: "han",
		hp: 5,
		skills: ["qj_fenyue"],
	},
	qj_liuchongluojun: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_jingnu", "qj_weitun"],
	},
	qj_liuyao: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_kannan", "qj_niju"],
	},
	qj_jianshuo: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_jibing"],
	},
	//士兵
	yc_niujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_niujin"],
		isUnseen: true,
	},
	yc_zhoucang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_zhoucang"],
		isUnseen: true,
	},
	yc_quexiaojiang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_quexiaojiang"],
		isUnseen: true,
	},
	yc_wenhu: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_wenhu"],
		isUnseen: true,
	},
	yc_mushun: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_mushun"],
		isUnseen: true,
	},
	yc_huweijun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["qj_huweijun"],
		isUnseen: true,
	},
	yc_baimayicong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_baimayicong"],
		isUnseen: true,
	},
	yc_xiangbing: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["qj_xiangbing"],
		isUnseen: true,
	},
	yc_jinfanjun: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qj_jinfanjun"],
		isUnseen: true,
	},
	yc_bingzhoulangqi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["qj_bingzhoulangqi"],
		isUnseen: true,
	},
	yc_huangjinleishi: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["qj_huangjinleishi"],
		isUnseen: true,
	},
	yc_fuxinsishi: {
		sex: "male",
		group: "jin",
		hp: 4,
		skills: ["qj_fuxinsishi"],
		isUnseen: true,
	},
	yc_xiyuanjun: {
		sex: "male",
		group: "han",
		hp: 4,
		skills: ["qj_xiyuanjun"],
		isUnseen: true,
	},
};

for (let i in character) {
	character[i].img =
		"extension/乔剪国战/image/character/" + i.substring(3) + ".jpg";
}

export default character;
